import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "./Components/navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className="bg-[#252B42]"
        //className={`${geistSans.variable} ${geistMono.variable} antialiased`  }
      >
        <Navigation></Navigation>
        {children}
       </body>
    </html>
  );
}
